"""add: deleted email

Revision ID: 160095533e13
Revises: 9aec7efc27c9
Create Date: 2026-02-07 17:33:56.215137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "160095533e13"
down_revision: Union[str, Sequence[str], None] = "9aec7efc27c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("deleted_email", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_email")
    # ### end Alembic commands ###
