"""relationships

Revision ID: 5aca8fc9182f
Revises: 96565b4a4090
Create Date: 2026-01-24 19:27:46.763180

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "5aca8fc9182f"
down_revision: Union[str, Sequence[str], None] = "96565b4a4090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
