"""relationships

Revision ID: 96565b4a4090
Revises: eca6b8503a88
Create Date: 2026-01-24 19:25:19.069590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96565b4a4090"
down_revision: Union[str, Sequence[str], None] = "eca6b8503a88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "professions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("profession_id", sa.BigInteger(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("posts_count", sa.BigInteger(), nullable=False),
        sa.Column("posts_read_count", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profession_id"],
            ["professions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "comments",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("post", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.add_column("post", sa.Column("category_id", sa.BigInteger(), nullable=True))
    op.add_column("post", sa.Column("views_count", sa.BigInteger(), nullable=False))
    op.add_column("post", sa.Column("likes_count", sa.BigInteger(), nullable=False))
    op.add_column("post", sa.Column("comments_count", sa.BigInteger(), nullable=False))
    op.add_column("post", sa.Column("mins_read", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "post", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "post", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_column("post", "mins_read")
    op.drop_column("post", "comments_count")
    op.drop_column("post", "likes_count")
    op.drop_column("post", "views_count")
    op.drop_column("post", "category_id")
    op.drop_column("post", "user_id")
    op.drop_table("comments")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("professions")
    op.drop_table("categories")
    # ### end Alembic commands ###
