"""empty message

Revision ID: cf86efca6c77
Revises: f3e78f64cc29
Create Date: 2026-01-28 18:58:21.368067

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cf86efca6c77"
down_revision: Union[str, Sequence[str], None] = "f3e78f64cc29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
