"""relationships

Revision ID: df497e39a484
Revises: 5aca8fc9182f
Create Date: 2026-01-26 00:42:59.536216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df497e39a484"
down_revision: Union[str, Sequence[str], None] = "5aca8fc9182f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("post_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "comments", "post", ["post_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "post_id")
    # ### end Alembic commands ###
