"""some changes

Revision ID: f3e78f64cc29
Revises: df497e39a484
Create Date: 2026-01-28 16:31:41.247186

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f3e78f64cc29"
down_revision: Union[str, Sequence[str], None] = "df497e39a484"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
